### ISSUE TITLE
Aggregate online and aggregate offline functionality is not working

### ISSUE THREAD

**Issue by nidhimittalhada** [puppetlabs/puppetlabs-netapp#108]
Aggregate online and aggregate offline functionality is not working.

**Step to reproduce:**

We have an aggregate "wipro_aggr" already created and is in "online" state. We are trying to make the aggregate offline by using the "state" property as "offline" in puppet manifest.

**manifest(site.pp)**

node 'hnidhi-vsim1' {
  netapp_aggregate {'wipro_aggr':
    ensure => 'present',
    blocktype => '64_bit',
    checksumstyle => 'block',
    diskcount => '3',
    option_free_space_realloc => 'off',
    state => 'offline',
    nodes => ['hnidhi-vsim1']
  }
}
node 'data_vserver2' {
}

**puppet run device command**
puppet device --user=root --verbose

**Expected result:**
aggregate wipro_aggr should be in offline state.

**Actual result:**
aggregate wipro_aggr still is in online state.

**VSIM log**
_before running puppet device command:_
hnidhi-vsim12::> aggr show
                                                                      
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
wipro_aggr 112.1MB   111.9MB    0% online       0 hnidhi-vsim1     raid4,
                                                                   normal

_after running puppet device command_
hnidhi-vsim12::> aggr show
                                                                    
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------

wipro_aggr 112.1MB   111.9MB    0% online       0 hnidhi-vsim1     raid4,
                                                                   normal
                                                                   

The same is happening when trying to make an aggregate online from offline state.

**Comment by hunner** [comment]
Merged!
