### ISSUE TITLE
Error while deleting quota entry

### ISSUE THREAD

**Issue by nidhimittalhada** [puppetlabs/puppetlabs-netapp#114]
vol quota status is on and we are trying to delete quota entry.
It gives error as :
Could not evaluate: Executing api call quota-resize volume t_vol failed: "No valid quota rules found in quota policy default for volume t_vol in Vserver data_vserver2. ".

**manifest(site.pp)**
node 'hnidhi-vsim1' {
}
node 'data_vserver2' {
  netapp_quota { '/vol/t_vol/test_qtree':
    ensure    => absent,
    type      => tree,
    volume    => 't_vol',
    disklimit => '10G',
  }
}

**Comment by hunner** [comment]
Merged!
