### ISSUE TITLE
Cannot create qtree with same name on 2 different volume

### ISSUE THREAD

**Issue by fduranti** [puppetlabs/puppetlabs-netapp#77]
It seems that it's not possible to create a qtree with the same name on 2 different volume on the same SVM using this module.
Normally it's possible to do this on a NetApp.

I'm trying to define the resource with different title using the resource name to define the qtree but it don't work.

This is the code (line 18 and 23 are the 2 netapp_qtree definition:

```
    netapp_export_policy { "nfs":
      ensure => present,
      }

    netapp_export_rule { "nfs:1":
      ensure            => present,
      clientmatch       => "10.0.0.0/8",
      protocol          => ["nfs"],
      superusersecurity => "none",
      rorule            => ["sys","none"],
      rwrule            => ["sys","none"],
    }

    netapp_qtree {"voltst11_pippo1":
      volume       => 'voltst11',
      name         => 'pippo1',
      exportpolicy => "nfs",
    }

    netapp_qtree {"voltst12_pippo1":
      volume       => 'voltst12',
      name         => 'pippo1',
      exportpolicy => "nfs",
    }

```

This is the error i get 

> Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Cannot alias Netapp_qtree[voltst12_pippo1] to ["pippo1"] at /etc/puppetlabs/code/environments/development/site/profile/manifests/storage/netapp.pp:23; resource ["Netapp_qtree", "pippo1"] already declared at /etc/puppetlabs/code/environments/development/site/profile/manifests/storage/netapp.pp:18 at /etc/puppetlabs/code/environments/development/site/profile/manifests/storage/netapp.pp:23:5 on node itnapsvmtest01.q8int.com

**Comment by fduranti** [comment]
No one have this issue? It's not possible with this module to create qtree with the same name on different volumes. Using normal commandline or gui on netapp storage you can create them without problem.

**Comment by jboero** [comment]
Just an update on this one - this is expected behavior for Puppet sadly.  Redefining a new resource with the same name is interpreted by Puppet as a collision and it thinks there is an error.  This module may need to be refactored to use a different unique ID for name while maintaining the NetApp attributes.
